// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: heartbeats.proto

package HeartBeats

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_heartbeats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_heartbeats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_heartbeats_proto_rawDescGZIP(), []int{0}
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_heartbeats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_heartbeats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_heartbeats_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

var File_heartbeats_proto protoreflect.FileDescriptor

const file_heartbeats_proto_rawDesc = "" +
	"\n" +
	"\x10heartbeats.proto\x12\n" +
	"heartbeats\"\a\n" +
	"\x05Empty\"+\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId2P\n" +
	"\x10HeartbeatService\x12<\n" +
	"\tKeepAlive\x12\x1c.heartbeats.HeartbeatRequest\x1a\x11.heartbeats.EmptyBCZAgithub.com/RawanMostafa08/Distributed-File-System/grpc/HeartBeatsb\x06proto3"

var (
	file_heartbeats_proto_rawDescOnce sync.Once
	file_heartbeats_proto_rawDescData []byte
)

func file_heartbeats_proto_rawDescGZIP() []byte {
	file_heartbeats_proto_rawDescOnce.Do(func() {
		file_heartbeats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_heartbeats_proto_rawDesc), len(file_heartbeats_proto_rawDesc)))
	})
	return file_heartbeats_proto_rawDescData
}

var file_heartbeats_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_heartbeats_proto_goTypes = []any{
	(*Empty)(nil),            // 0: heartbeats.Empty
	(*HeartbeatRequest)(nil), // 1: heartbeats.HeartbeatRequest
}
var file_heartbeats_proto_depIdxs = []int32{
	1, // 0: heartbeats.HeartbeatService.KeepAlive:input_type -> heartbeats.HeartbeatRequest
	0, // 1: heartbeats.HeartbeatService.KeepAlive:output_type -> heartbeats.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_heartbeats_proto_init() }
func file_heartbeats_proto_init() {
	if File_heartbeats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_heartbeats_proto_rawDesc), len(file_heartbeats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_heartbeats_proto_goTypes,
		DependencyIndexes: file_heartbeats_proto_depIdxs,
		MessageInfos:      file_heartbeats_proto_msgTypes,
	}.Build()
	File_heartbeats_proto = out.File
	file_heartbeats_proto_goTypes = nil
	file_heartbeats_proto_depIdxs = nil
}
