// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: replicate.proto

package replicate

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DFS_NotifyMachineDataTransferService_FullMethodName = "/replicate.DFS/notifyMachineDataTransferService"
)

// DFSClient is the client API for DFS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DFSClient interface {
	NotifyMachineDataTransferService(ctx context.Context, in *MachineDataTransferRequest, opts ...grpc.CallOption) (*MachineDataTransferResponse, error)
}

type dFSClient struct {
	cc grpc.ClientConnInterface
}

func NewDFSClient(cc grpc.ClientConnInterface) DFSClient {
	return &dFSClient{cc}
}

func (c *dFSClient) NotifyMachineDataTransferService(ctx context.Context, in *MachineDataTransferRequest, opts ...grpc.CallOption) (*MachineDataTransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MachineDataTransferResponse)
	err := c.cc.Invoke(ctx, DFS_NotifyMachineDataTransferService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DFSServer is the server API for DFS service.
// All implementations must embed UnimplementedDFSServer
// for forward compatibility.
type DFSServer interface {
	NotifyMachineDataTransferService(context.Context, *MachineDataTransferRequest) (*MachineDataTransferResponse, error)
	mustEmbedUnimplementedDFSServer()
}

// UnimplementedDFSServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDFSServer struct{}

func (UnimplementedDFSServer) NotifyMachineDataTransferService(context.Context, *MachineDataTransferRequest) (*MachineDataTransferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyMachineDataTransferService not implemented")
}
func (UnimplementedDFSServer) mustEmbedUnimplementedDFSServer() {}
func (UnimplementedDFSServer) testEmbeddedByValue()             {}

// UnsafeDFSServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DFSServer will
// result in compilation errors.
type UnsafeDFSServer interface {
	mustEmbedUnimplementedDFSServer()
}

func RegisterDFSServer(s grpc.ServiceRegistrar, srv DFSServer) {
	// If the following call pancis, it indicates UnimplementedDFSServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DFS_ServiceDesc, srv)
}

func _DFS_NotifyMachineDataTransferService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MachineDataTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DFSServer).NotifyMachineDataTransferService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DFS_NotifyMachineDataTransferService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DFSServer).NotifyMachineDataTransferService(ctx, req.(*MachineDataTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DFS_ServiceDesc is the grpc.ServiceDesc for DFS service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DFS_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "replicate.DFS",
	HandlerType: (*DFSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "notifyMachineDataTransferService",
			Handler:    _DFS_NotifyMachineDataTransferService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "replicate.proto",
}
